### ISSUE TITLE
Are you in 5 or 2 GitHub organisations?

### ISSUE THREAD

**Issue by rugk** [austinhuang0131/austinhuang0131#6]
https://github.com/austinhuang0131/austinhuang0131/blob/master/github-metrics.svg shows:
![grafik](https://github.com/austinhuang0131/austinhuang0131/assets/11966684/26b2821e-758f-4672-b82d-e1031ddc0c82)

says you are in 5 orgs …

…but on https://github.com/austinhuang0131 you are only listed as being in two:
![grafik](https://github.com/austinhuang0131/austinhuang0131/assets/11966684/67b36ec3-3f72-4452-a667-becfadbdfc64)

**Comment by austinhuang0131** [comment]
i am indeed in 5 organizations, but github allows you to change visibility of your membership

<img width="1389" alt="Screenshot 2023-08-21 at 18 28 12" src="https://github.com/austinhuang0131/austinhuang0131/assets/16656689/3d5d2d75-5bbe-446c-b571-b66a13e1d275">

the organizations don't really matter but since i don't really work in them anymore i'll hide some more

**Comment by rugk** [comment]
Yeah the stats may be confusing then just but okay thx FYI.
